# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: DataScience for Beginner
email: byungjun0689@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This WebPages are about Various Data Analytics Tech for Beginner

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://byungjun0689.github.io" # the base hostname & protocol for your site

#sidebar
default-image: webjeda-logo-big.jpg # If there is no featured image in a post then this image will be showed. Also on all pages this image will be showed. Use a 500x250 image.

#footer
built-by: Lee Byungjun
copyright:
   name: JunL
   link: 'http://jtoday.tistory.com/'

# Build settings
markdown: kramdown
permalink: /:title/
paginate: 6
paginate_path: /page:num/

# Tracker
google_analytics_id: UA-100783503-1

# Comments
#disqus-shortname: webjeda-demo

#social
facebook: http://facebook.com/2byungjun
#quora: http://quora.com/sharathdt
#twitter: http://twitter.com/@webjeda
github: http://github.com/byungjun0689

#facebook like box
fb-app-id: 1055189901193516
fb-page-url: https://www.facebook.com/2byungjun/
fb-page-title: 2byungjun

# Sass style
sass:
  style: compressed

# Ruby Gems
gems: [jekyll-paginate, jekyll-seo-tag]

